name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize]

jobs:
  # Cancel Previous Redundant Builds
  avoid_redundancy:
    runs-on: ubuntu-18.04
    permissions:
      actions: write
    steps:
      - name: Cancelando Compilaciones Anteriores Redundantes
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{github.token}}

  # Assigns the event creator to the PR
  assign_pr_owner:
    runs-on: ubuntu-latest
    steps:
      - name: Asignando PR al creador
        uses: thomaseizinger/assign-pr-creator-action@v1.0.0
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        with:
          repo-token: ${{ secrets.USER_TOKEN }}

  # Install Node and creating cache
  install:
    runs-on: ubuntu-18.04
    steps:
      - name: Descargando Repositorio
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Instalando NodeJS v16
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: Instalando Dependencias
        run: npm install --no-audit --no-fund --no-optional

  # Lint the code
  lint:
    needs: [install]
    runs-on: ubuntu-18.04
    steps:
      - name: Descargando Repositorio
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Instalando NodeJS v16
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: Instalando Dependencias
        run: npm install --no-audit --no-fund --no-optional
      - name: Ejectuando Chequeo de Codigo (LINT)
        run: npm run lint

  # Creates a build and uploads an artifact
  build:
    needs: [install]
    runs-on: ubuntu-18.04
    steps:
      - name: Descargando Repositorio
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Instalando NodeJS v16
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: Instalando Dependencias
        run: npm install --no-audit --no-fund --no-optional
      - name: Empaquetando Aplicacion (BUILD)
        run: npm run build
      - name: Comprimiendo Carpeta del Bundle
        run: tar -zcvf dist.tar.gz ./dist/
      - name: Guardando Artefacto
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist.tar.gz

  # Deploy to Heroku
  deploy:
    needs: [lint, build]
    runs-on: ubuntu-18.04
    # environment:
    #   name: ${{ github.event_name != 'pull_request' && 'Production' || 'Preview'}}
    #   url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Descargando Repositorio
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Instalando NodeJS v16
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16'
      - name: Descargando Artefacto
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: .
      - name: Descomprimiendo Artefacto
        run: |
          tar -zxvf ./dist.tar.gz
          rm ./dist.tar.gz
      - name: Desplegando en HEROKU (DEPLOY)
        if: ${{github.event_name == 'push'}}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
          healthcheck: 'https://${{secrets.HEROKU_APP}}.herokuapp.com/health'
          rollbackonhealthcheckfailed: true
          delay: 5
